export const INITIAL_KOMODITAS = [
  { id: 'kom-1', nama: 'Tomat (Tomato)', satuan: 'kg', icon: 'tomato', avgPrice: 12000, trend: 'up', color: 'bg-rose-500 text-white' },
  { id: 'kom-2', nama: 'Cabai Merah (Chili)', satuan: 'kg', icon: 'chili', avgPrice: 35000, trend: 'down', color: 'bg-red-600 text-white' },
  { id: 'kom-3', nama: 'Padi (Rice)', satuan: 'kg', icon: 'rice', avgPrice: 14000, trend: 'stable', color: 'bg-amber-500 text-white' },
  { id: 'kom-4', nama: 'Jagung (Corn)', satuan: 'kg', icon: 'corn', avgPrice: 8500, trend: 'up', color: 'bg-yellow-500 text-white' },
  { id: 'kom-5', nama: 'Bawang Merah (Shallot)', satuan: 'kg', icon: 'shallot', avgPrice: 28000, trend: 'up', color: 'bg-purple-500 text-white' },
  { id: 'kom-6', nama: 'Kubis (Cabbage)', satuan: 'kg', icon: 'cabbage', avgPrice: 6000, trend: 'stable', color: 'bg-emerald-500 text-white' },
];

export const INITIAL_PLOTS = [
  {
    id: 'plot-1',
    plot_name: 'Plot A - Lahan Utama',
    komoditas_id: 'kom-1',
    komoditas_nama: 'Tomat (Tomato)',
    komoditas_icon: 'tomato',
    area: 1200,
    location: 'Cangar, Bumiaji, Batu',
    planting_date: '2026-06-01',
    estimated_harvest_date: '2026-08-25',
    current_growth_stage: 'Flowering (Berbunga)',
    growth_progress: 65,
    status: 'urgent',
    status_text: 'Penyiraman tertunda (Watering overdue)',
    priority_score: 95,
    last_watered: '2 hari lalu',
    last_fertilized: '8 hari lalu',
    updated_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: 'plot-2',
    plot_name: 'Plot B - Lereng Selatan',
    komoditas_id: 'kom-2',
    komoditas_nama: 'Cabai Merah (Chili)',
    komoditas_icon: 'chili',
    area: 800,
    location: 'Pujon, Malang',
    planting_date: '2026-05-15',
    estimated_harvest_date: '2026-08-10',
    current_growth_stage: 'Fruiting (Pembuahan)',
    growth_progress: 80,
    status: 'attention',
    status_text: 'Jadwal pemupukan besok (Fertilization due tomorrow)',
    priority_score: 70,
    last_watered: 'Kemarin',
    last_fertilized: '14 hari lalu',
    updated_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
  },
  {
    id: 'plot-3',
    plot_name: 'Plot C - Lembah Sejuk',
    komoditas_id: 'kom-3',
    komoditas_nama: 'Padi (Rice)',
    komoditas_icon: 'rice',
    area: 2500,
    location: 'Dau, Malang',
    planting_date: '2026-06-20',
    estimated_harvest_date: '2026-10-15',
    current_growth_stage: 'Vegetative (Pertumbuhan Daun)',
    growth_progress: 35,
    status: 'ontrack',
    status_text: 'Kondisi stabil, tidak ada aksi mendesak',
    priority_score: 30,
    last_watered: 'Hari ini',
    last_fertilized: '5 hari lalu',
    updated_at: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
  },
  {
    id: 'plot-4',
    plot_name: 'Plot D - Kebun Atas',
    komoditas_id: 'kom-5',
    komoditas_nama: 'Bawang Merah (Shallot)',
    komoditas_icon: 'shallot',
    area: 650,
    location: 'Tulungrejo, Bumiaji, Batu',
    planting_date: '2026-07-01',
    estimated_harvest_date: '2026-09-01',
    current_growth_stage: 'Seedling (Pembibitan)',
    growth_progress: 20,
    status: 'ontrack',
    status_text: 'Kelembaban tanah optimal',
    priority_score: 25,
    last_watered: 'Hari ini',
    last_fertilized: '10 hari lalu',
    updated_at: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
  }
];

export const INITIAL_ACTIONS = [
  {
    id: 'act-1',
    plot_id: 'plot-1',
    plot_name: 'Plot A - Lahan Utama',
    komoditas_icon: 'tomato',
    title: 'Siram Tanaman (Watering)',
    description: 'Kelembaban tanah di bawah 40%. Segera lakukan penyiraman pagi/sore.',
    status: 'overdue',
    due_text: 'Terlewat 1 hari (Overdue)',
    priority: 'high',
    activity_type: 'Watering',
  },
  {
    id: 'act-2',
    plot_id: 'plot-2',
    plot_name: 'Plot B - Lereng Selatan',
    komoditas_icon: 'chili',
    title: 'Pupuk Susulan NPK (Fertilize)',
    description: 'Fase pembuahan membutuhkan nutrisi tambahan NPK cair 2 gr/liter.',
    status: 'today',
    due_text: 'Hari ini (Due Today)',
    priority: 'medium',
    activity_type: 'Fertilizing',
  },
  {
    id: 'act-3',
    plot_id: 'plot-1',
    plot_name: 'Plot A - Lahan Utama',
    komoditas_icon: 'tomato',
    title: 'Inspeksi Hama Kutu Putih (Pest Check)',
    description: 'Periksa bagian bawah daun terhadap serangan kutu kebul/putih.',
    status: 'today',
    due_text: 'Hari ini (Due Today)',
    priority: 'medium',
    activity_type: 'Pest Inspection',
  },
  {
    id: 'act-4',
    plot_id: 'plot-3',
    plot_name: 'Plot C - Lembah Sejuk',
    komoditas_icon: 'rice',
    title: 'Pembersihan Gulma (Weeding)',
    description: 'Bersihkan rumput liar di sekitar pematang dan saluran air.',
    status: 'soon',
    due_text: 'Besok (Due Tomorrow)',
    priority: 'low',
    activity_type: 'Weeding',
  }
];

export const INITIAL_ACTIVITIES = [
  {
    id: 'hist-1',
    plot_id: 'plot-1',
    plot_name: 'Plot A - Lahan Utama',
    komoditas_icon: 'tomato',
    activity_type: 'Watering',
    title: 'Penyiraman Rutin Pagi',
    notes: 'Volume 500 liter, irigasi tetes berjalan lancar.',
    date: 'Kemarin, 07:30 WIB',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    id: 'hist-2',
    plot_id: 'plot-2',
    plot_name: 'Plot B - Lereng Selatan',
    komoditas_icon: 'chili',
    activity_type: 'Fertilizing',
    title: 'Pemberian Pupuk Organik Cair',
    notes: 'Aplikasi semprot foliar pada masa vegetatif akhir.',
    date: '2 hari lalu, 16:00 WIB',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
  },
  {
    id: 'hist-3',
    plot_id: 'plot-3',
    plot_name: 'Plot C - Lembah Sejuk',
    komoditas_icon: 'rice',
    activity_type: 'Pest Inspection',
    title: 'Pemeriksaan Penggerek Batang',
    notes: 'Kondisi daun aman, tidak ditemukan tanda serangan hama wereng/penggerek.',
    date: '3 hari lalu, 08:15 WIB',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
  }
];

export const WEATHER_PREVIEW = {
  temp: 28,
  condition: 'Cerah Berawan (Partly Cloudy)',
  icon: 'partly_cloudy',
  humidity: 72,
  windSpeed: 14,
  rainProbability: 25,
  advisory: 'Kondisi cuaca ideal untuk penyiraman dan pemupukan luar ruangan pagi hari.',
};

export const INITIAL_NEWS = [
  {
    id: 'news-1',
    title: 'Panduan Mengatasi Kutu Kebul pada Tanaman Tomat & Cabai',
    category: 'Pengendalian Hama',
    date: '15 Juli 2026',
    readTime: '4 menit',
    image: 'https://images.unsplash.com/photo-1592878904946-b3cd8ae243d0?auto=format&fit=crop&w=600&q=80',
    summary: 'Kutu kebul merupakan vektor utama virus kuning yang berbahaya. Pelajari rotasi insektisida dan perangkap kuning untuk proteksi optimal.',
    content: `Serangan kutu kebul (Bemisia tabaci) pada musim pancaroba sering kali memicu meledaknya penyakit virus kuning (geminivirus) pada tanaman tomat dan cabai.\n\nLangkah preventif yang disarankan oleh pakar agronomi:\n1. Pemasangan Yellow Sticky Trap (Perangkap Kuning) sebanyak 40-50 buah per hektar untuk memonitor populasi hama dewasa.\n2. Sanitasi gulma di sekitar lahan yang sering menjadi inang cadangan kutu kebul.\n3. Gunakan insektisida botani berbahan aktif azadirachtin atau minyak mimba sebelum aplikasi kimiawi.\n4. Pastikan pemupukan kalium (K) cukup untuk memperkuat dinding sel daun.`
  },
  {
    id: 'news-2',
    title: 'Tren Harga Sayuran Dataran Tinggi Kuartal III 2026',
    category: 'Analisis Pasar',
    date: '14 Juli 2026',
    readTime: '3 menit',
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=600&q=80',
    summary: 'Permintaan pasar melonjak untuk komoditas tomat dan bawang merah. Cek analisis fluktuasi harga antar sentra produksi.',
    content: `Berdasarkan data harga komoditas regional, terjadi peningkatan permintaan signifikan di pasar induk kota-kota besar untuk cabai merah dan bawang merah.\n\nFaktor pendorong naik-turunnya harga saat ini:\n- Curah hujan lokal yang sempat tinggi di beberapa sentra pasokan utama membatasi panen serentak.\n- Biaya logistik dan distribusi yang stabil menjaga marjin petani tetap di kisaran 25-30% di atas biaya produksi (BEP).\n- Petani disarankan mengatur jadwal panen bertahap untuk memaksimalkan harga jual di puncak permintaan minggu depan.`
  },
  {
    id: 'news-3',
    title: 'Optimasi Irigasi Tetes untuk Menghemat Air hingga 40%',
    category: 'Teknologi Tani',
    date: '12 Juli 2026',
    readTime: '5 menit',
    image: 'https://images.unsplash.com/photo-1628352081506-83c43123ed6d?auto=format&fit=crop&w=600&q=80',
    summary: 'Penerapan irigasi tetes sederhana dengan timer otomatis mampu menstabilkan kelembaban akar tanpa mengikis nutrisi tanah.',
    content: `Irigasi tetes (drip irrigation) tidak lagi hanya untuk lahan berskala industri besar. Petani mandiri kini dapat menerapkan sistem irigasi selang pipa PE dengan dripper terkalibrasi.\n\nKeuntungan utama:\n- Efisiensi air meningkat pesat, mengurangi penguapan sia-sia di siang hari.\n- Fertigasi (pemupukan lewat saluran air) dapat dilakukan secara presisi langsung ke zona perakaran.\n- Mengurangi pertumbuhan gulma karena air hanya menetes di dekat pangkal batang tanaman utama.`
  }
];
